import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ink: '#2A2420',
        // Material-3-style tokens from the Stitch design export
        // (docs/superpowers/specs/2026-09-18-stitch-foundation-design.md).
        surface: '#faf8f5',
        'surface-dim': '#ddd6ce',
        'surface-bright': '#faf8f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f1ec',
        'surface-container': '#eeeae4',
        'surface-container-high': '#e7e2db',
        'surface-container-highest': '#dfd9d1',
        'on-surface': '#1d1a17',
        'on-surface-variant': '#58504a',
        'inverse-surface': '#352f2e',
        'inverse-on-surface': '#f9eeec',
        outline: '#6b5f58',
        'outline-variant': '#d8d0c7',
        // Card edges: a hairline replaces the old pink offset shadow.
        hairline: '#e6e0d8',
        'surface-tint': '#ad3217',
        primary: '#aa3015',
        'on-primary': '#ffffff',
        'primary-container': '#cc482b',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb4a4',
        secondary: '#48645d',
        'on-secondary': '#ffffff',
        'secondary-container': '#c7e6dd',
        'on-secondary-container': '#4c6861',
        tertiary: '#825100',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a36700',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad3',
        'primary-fixed-dim': '#ffb4a4',
        'on-primary-fixed': '#3d0600',
        'on-primary-fixed-variant': '#8b1901',
        'secondary-fixed': '#cae9e0',
        'secondary-fixed-dim': '#aecdc4',
        'on-secondary-fixed': '#02201b',
        'on-secondary-fixed-variant': '#304c46',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        background: '#faf8f5',
        'on-background': '#1d1a17',
        'surface-variant': '#dfd9d1',
      },
      fontFamily: {
        // Noto Sans KR is a fallback, not a duplicate: "Plus Jakarta Sans"/
        // "Noto Sans" ship no Hangul glyphs, so without it every Korean
        // character in this app would silently fall back to the OS default.
        heading: ['"Plus Jakarta Sans"', '"Noto Sans KR"', 'sans-serif'],
        body: ['"Noto Sans"', '"Noto Sans KR"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-sm': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '700' }],
        // 11px floor: Hangul below this stops being legible on phones.
        'label-sm': ['11px', { lineHeight: '15px', letterSpacing: '0.02em', fontWeight: '700' }],
        'stat-counter': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      spacing: {
        gutter: '0.75rem',
        'gutter-mobile': '0.5rem',
        margin: '1rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.875rem',
        'space-lg': '1.25rem',
        'space-xl': '1.75rem',
      },
      borderRadius: {
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
      },
      boxShadow: {
        card: '0 1px 2px rgba(29,26,23,0.04)',
        float: '0 10px 28px -8px rgba(29,26,23,0.28)',
      },
      keyframes: {
        'ring-glow': {
          '0%, 100%': { transform: 'scale(0.9)', opacity: '0.6' },
          '50%': { transform: 'scale(1.15)', opacity: '1' },
        },
        'icon-cycle': {
          '0%': { opacity: '0', transform: 'scale(0.6) rotate(-8deg)' },
          '8%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
          '22%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
          '30%': { opacity: '0', transform: 'scale(0.6) rotate(8deg)' },
          '100%': { opacity: '0' },
        },
        'text-cycle': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '6%': { opacity: '1', transform: 'translateY(0)' },
          '27%': { opacity: '1', transform: 'translateY(0)' },
          '33%': { opacity: '0', transform: 'translateY(-6px)' },
          '100%': { opacity: '0' },
        },
        'scan-sweep': {
          '0%': { top: '-10%' },
          '50%': { top: '100%' },
          '100%': { top: '-10%' },
        },
        'burst-pop': {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '60%': { transform: 'scale(1.15)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '0.8' },
        },
        'badge-bounce': {
          '0%': { opacity: '0', transform: 'scale(0.6) rotate(-12deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
        },
        'point-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'confetti-fall': {
          '0%': { opacity: '0', transform: 'translateY(-20px) rotate(0deg)' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { opacity: '0', transform: 'translateY(380px) rotate(360deg)' },
        },
      },
      animation: {
        'ring-glow': 'ring-glow 1.8s ease-in-out infinite',
        'icon-cycle': 'icon-cycle 3.2s infinite',
        'text-cycle': 'text-cycle 4.8s infinite',
        'scan-sweep': 'scan-sweep 1.6s ease-in-out infinite',
        'burst-pop': 'burst-pop 0.6s ease-out both',
        'badge-bounce': 'badge-bounce 0.6s cubic-bezier(0.16,1,0.3,1) both',
        'point-in': 'point-in 0.5s 0.4s ease-out both',
        'confetti-fall': 'confetti-fall 2.2s ease-in infinite',
      },
    },
  },
  plugins: [],
} satisfies Config
