import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: '#E9DFC3',
        card: '#F8F2E2',
        ink: '#2A2420',
        stamp: '#B0472E',
        accent: '#3F6459',
        warn: '#B9822C',
        loc: {
          bathroom: '#6E8F87',
          kitchen: '#C98F2B',
          laundry: '#7D93A6',
          closet: '#B0472E',
          vanity: '#A9789A',
          bedroom: '#8A8F6E',
          livingroom: '#9C8B5E',
          entrance: '#6F7D5C',
          medicine: '#B0763F',
          car: '#5C7A8B',
        },
        // Material-3-style tokens from the Stitch design export
        // (docs/superpowers/specs/2026-09-18-stitch-foundation-design.md).
        // Additive only — used by later per-screen migration sub-projects.
        surface: '#fff8f6',
        'surface-dim': '#e2d8d6',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fcf1ef',
        'surface-container': '#f6ecea',
        'surface-container-high': '#f0e6e4',
        'surface-container-highest': '#eae0de',
        'on-surface': '#1f1b1a',
        'on-surface-variant': '#59413c',
        'inverse-surface': '#352f2e',
        'inverse-on-surface': '#f9eeec',
        outline: '#8d716a',
        'outline-variant': '#e1bfb8',
        'surface-tint': '#ad3217',
        primary: '#aa3015',
        'on-primary': '#ffffff',
        'primary-container': '#cc482b',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb4a4',
        secondary: '#48645d',
        'on-secondary': '#ffffff',
        'secondary-container': '#c7e6dd',
        'on-secondary-container': '#4c6861',
        tertiary: '#825100',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a36700',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad3',
        'primary-fixed-dim': '#ffb4a4',
        'on-primary-fixed': '#3d0600',
        'on-primary-fixed-variant': '#8b1901',
        'secondary-fixed': '#cae9e0',
        'secondary-fixed-dim': '#aecdc4',
        'on-secondary-fixed': '#02201b',
        'on-secondary-fixed-variant': '#304c46',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        background: '#fff8f6',
        'on-background': '#1f1b1a',
        'surface-variant': '#eae0de',
      },
      fontFamily: {
        // Noto Sans KR is a fallback, not a duplicate: "Plus Jakarta Sans"/
        // "Noto Sans" ship no Hangul glyphs, so without it every Korean
        // character in this app would silently fall back to the OS default.
        heading: ['"Plus Jakarta Sans"', '"Noto Sans KR"', 'sans-serif'],
        body: ['"Noto Sans"', '"Noto Sans KR"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-sm': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '800' }],
        'stat-counter': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      spacing: {
        gutter: '0.75rem',
        'gutter-mobile': '0.5rem',
        margin: '1rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.875rem',
        'space-lg': '1.25rem',
        'space-xl': '1.75rem',
      },
      boxShadow: {
        chunky: '4px 4px 0 0 #2A2420',
        'elevation-1': '0px 3px 0px rgba(43,38,37,0.08)',
        'elevation-2': '0px 4px 0px #1E3A34',
        'elevation-3': '0px 4px 0px #A3361E',
        'elevation-4': '0px 12px 24px -4px rgba(30,58,52,0.12), 0px 4px 0px #1E3A34',
      },
    },
  },
  plugins: [],
} satisfies Config
